spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.28.144.4/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.28.144.4
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx6b108bf4cc0a136d
  mpAppSecret: 892b727d50ae36b276519e55d0a8f866
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sellwy.s1.natapp.cc/sell/pay/notify

project-url:
  wechatMpAuthorize: http://sellwy.s1.natapp.cc
  wechatOpenAuthorize: http://sellwy.s1.natapp.cc
  sell: http://sellwy.s1.natapp.cc
